
publications:
  - url: https://nuget.org/packages/LaunchDarkly.Logging.Microsoft
    description: NuGet

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows
  env:
    LD_RELEASE_TEST_TARGET_FRAMEWORK: netstandard2.1
    LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.1

documentation:
  title: LaunchDarkly Logging API for .NET - Microsoft.Extensions.Logging Adapter
  githubPages: true

releasableBranches:
  - name: master
  - name: 1.x
