version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.Logging.Microsoft
    description: NuGet

jobs:
  - docker:
      image: ldcircleci/dotnet6-release:1
    template:
      name: dotnet-linux
    env:
      TESTFRAMEWORK: net6.0
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.1

documentation:
  title: LaunchDarkly Logging API for .NET - Microsoft.Extensions.Logging Adapter
  gitHubPages: true

branches:
  - name: main
  - name: 2.x
  - name: 1.x
